"""
    ThyStreet

    Thy Street APIs are completely RESTful and all our responses are returned in JSON.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@thystreet.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import thystreet
from thystreet.model.order_status_dto import OrderStatusDto


class TestOrderStatusDto(unittest.TestCase):
    """OrderStatusDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderStatusDto(self):
        """Test OrderStatusDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrderStatusDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
