"""
    ThyStreet

    Thy Street APIs are completely RESTful and all our responses are returned in JSON.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@thystreet.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import thystreet
from thystreet.model.device_status_dto import DeviceStatusDto


class TestDeviceStatusDto(unittest.TestCase):
    """DeviceStatusDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceStatusDto(self):
        """Test DeviceStatusDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeviceStatusDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
