"""
    Thy Street

    These are API's to easily manage your Thy Street device public pages. Thy Street APIs are completely RESTful and all our responses are returned in JSON.  # noqa: E501

    The version of the OpenAPI document: 0.0.2
    Contact: support@thystreet.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import thystreet
from thystreet.model.set_device_details_dto import SetDeviceDetailsDto


class TestSetDeviceDetailsDto(unittest.TestCase):
    """SetDeviceDetailsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetDeviceDetailsDto(self):
        """Test SetDeviceDetailsDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SetDeviceDetailsDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
