"""
    ThyStreet

    Thy Street APIs are completely RESTful and all our responses are returned in JSON.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@thystreet.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import thystreet
from thystreet.api.order_api import OrderApi  # noqa: E501


class TestOrderApi(unittest.TestCase):
    """OrderApi unit test stubs"""

    def setUp(self):
        self.api = OrderApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_set_status(self):
        """Test case for set_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
