"""
    ThyStreet

    Thy Street APIs are completely RESTful and all our responses are returned in JSON.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: support@thystreet.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "thystreet"
VERSION = "0.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="ThyStreet",
    author="Support",
    author_email="support@thystreet.com",
    url="https://pypi.org/project/thystreet/",
    keywords=["OpenAPI", "OpenAPI-Generator", "ThyStreet"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    Thy Street APIs are completely RESTful and all our responses are returned in JSON.  # noqa: E501
    """
)
